create table
  public.notifications (
    id bigint generated by default as identity not null,
    timestamp timestamp with time zone not null default now(),
    content text not null,
    userUID uuid not null,
    type bigint null,
    constraint notification_pkey primary key (id),
    constraint notifications_userUID_fkey foreign key ("userUID") references players (uid)
  ) tablespace pg_default;